### ISSUE TITLE
package:// syntax in URDF

### ISSUE THREAD

**Issue by stephane-caron** [shbang91/draco3_description#1]
According to the URDF "spec", mesh filenames like:
```xml
        <mesh filename="package://meshes/torso_link3.obj"/>
```
Should use a fully-qualified ``package://NAME_OF_PACKAGE/path`` (see e.g. [this tutorial](https://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch)). Here that would be:
```xml
        <mesh filename="package://draco3_description/meshes/torso_link3.obj"/>
```

It's not a biggie since most URDF loaders add hacks around having/not having `package://`, but sometimes the hacks don't cover all cases :sweat_smile:

In this instance, ``python show_in_yourdfpy.py draco3`` fails in [robot_descriptions](https://github.com/robot-descriptions/robot_descriptions.py/tree/master/examples) because of an edge case https://github.com/clemense/yourdfpy/issues/43 (but this edge case is not triggered if the `package://` URI is fully formed).

**Comment by shbang91** [comment]
Thank you for the feedback. I pushed the changes based on your comment.

**Comment by stephane-caron** [comment]
And ``python show_in_yourdfpy.py draco3`` now works :+1: Thanks!
